CREATE TABLE /*TABLE_PREFIX*/t_nc_subscriber (
    pk_subs_id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    subs_email VARCHAR(100),
     PRIMARY KEY (pk_subs_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';